Document workflow
UniversityOfIowaHealthCare/cosmetic-surgery-redone pull request #10
Opened 2019-01-08 19:11 UTC by SamUndefined

2019-01-09 20:43 UTC, ralphnahra submitted a review, later dismissed
All makes sense.

2019-01-10 20:33 UTC, augustshultz requested changes

2019-01-11 00:50 UTC, SamUndefined commented on README.md
> +* **Always feel free to ask any questions you have or to challenge this process if you have ideas to imrpove it**
ur a typo

2019-01-11 14:09 UTC, augustshultz commented on README.md
> +* **Always feel free to ask any questions you have or to challenge this process if you have ideas to imrpove it**
Who told you that!? Did my mother tell you that?! She promised she wouldn't say that anymore.

2019-01-11 14:12 UTC, augustshultz approved these changes

2019-01-11 14:13 UTC, merged